// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// Prisma CLI a veces "detecta" este config y omite la carga automática de .env.
// Forzamos la carga aquí para que `DATABASE_URL` y demás estén disponibles.
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  engine: 'classic',
  datasource: {
    url: env('DATABASE_URL'),
  },
});
